# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trans.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Trans.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bTrans.proto\x12\x07lecture\"x\n\nAudioChunk\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\x12\x12\n\nspeaker_id\x18\x02 \x01(\t\x12\x1a\n\x12is_cloud_processed\x18\x03 \x01(\x08\x12\x11\n\ttext_data\x18\x04 \x01(\t\x12\x15\n\rlanguage_code\x18\x05 \x01(\t\"b\n\x10\x42roadcastMessage\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08subtitle\x18\x02 \x01(\t\x12\x15\n\rlanguage_code\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"=\n\x0eStudentRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t2[\n\x0f\x41iWorkerService\x12H\n\x12ProcessTranslation\x12\x13.lecture.AudioChunk\x1a\x19.lecture.BroadcastMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Trans_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=24
  _globals['_AUDIOCHUNK']._serialized_end=144
  _globals['_BROADCASTMESSAGE']._serialized_start=146
  _globals['_BROADCASTMESSAGE']._serialized_end=244
  _globals['_STUDENTREQUEST']._serialized_start=246
  _globals['_STUDENTREQUEST']._serialized_end=307
  _globals['_AIWORKERSERVICE']._serialized_start=309
  _globals['_AIWORKERSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
